input.onButtonPressed(Button.A, function () {
    led.unplot(0, 2)
    led.plot(1, 1)
    basic.pause(500)
    led.unplot(1, 1)
    led.plot(2, 0)
    basic.pause(500)
    led.unplot(2, 0)
    led.plot(3, 1)
    basic.pause(500)
    led.unplot(3, 1)
    led.plot(4, 2)
    basic.pause(500)
})
input.onButtonPressed(Button.B, function () {
    led.unplot(4, 2)
    led.plot(3, 3)
    basic.pause(500)
    led.unplot(3, 3)
    led.plot(2, 4)
    basic.pause(500)
    led.unplot(2, 4)
    led.plot(1, 3)
    basic.pause(500)
    led.unplot(1, 3)
    led.plot(0, 2)
    basic.pause(500)
})
basic.forever(function () {
    let sprite: game.LedSprite = null
    if (sprite.isTouchingEdge() == true) {
        sprite.delete()
        basic.showString("GAME OVER")
    }
})
