input.onButtonPressed(Button.A, function () {
    sprite.change(LedSpriteProperty.X, 1)
    basic.pause(500)
    sprite.change(LedSpriteProperty.X, 1)
    basic.pause(500)
    sprite.change(LedSpriteProperty.X, 1)
    basic.pause(500)
    sprite.change(LedSpriteProperty.X, 1)
})
input.onButtonPressed(Button.AB, function () {
    sprite = game.createSprite(2, 2)
    basic.pause(500)
    sprite.change(LedSpriteProperty.X, 1)
    basic.pause(500)
    sprite.change(LedSpriteProperty.X, 1)
})
input.onButtonPressed(Button.B, function () {
    sprite.change(LedSpriteProperty.X, -1)
    basic.pause(500)
    sprite.change(LedSpriteProperty.X, -1)
    basic.pause(500)
    sprite.change(LedSpriteProperty.X, -1)
    basic.pause(500)
    sprite.change(LedSpriteProperty.X, -1)
})
let sprite: game.LedSprite = null
music.playMelody("C5 A E G C E B G ", 120)
